/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "ashmem.h"
#include "futex.h"

/* Header for class com_furture_myapplication_NativeIpc */

#ifndef _Included_com_furture_myapplication_NativeIpc
#define _Included_com_furture_myapplication_NativeIpc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_furture_myapplication_NativeIpc
 * Method:    ipc6
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_furture_myapplication_NativeIpc_ipc
(JNIEnv *, jclass, jbyteArray);

JNIEXPORT void JNICALL
Java_com_furture_myapplication_NativeIpc_exit(JNIEnv *env, jclass type);

#ifdef __cplusplus
}
#endif
#endif
